name: Publish from Master
env:
  HOST: makhekh.com
  THE_ENV: production
  URL: https://makhekh.com/
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Confirm start'     
        required: false
        default: 'yes'
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: prelive
      url: ${{ env.URL }}
    steps:
      - uses: actions/checkout@v4
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy
        run: |

          rsync -e "ssh -o StrictHostKeyChecking=no" -crvl  --delete \
          --exclude=/node_modules \
          --exclude=/public/storage \
          --exclude=/.env \
          --exclude=/.git* \
          ./ root@${{ env.HOST }}:/root/frontend
          # Run artisan and composer commands
          ssh root@${{ env.HOST }} "
          docker compose build && docker compose up -d "
